# Generated by Django 4.2.21 on 2025-05-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration initiale pour l'application 'profiles'.

    Cette migration crée la structure de base de la table 'Profile' qui sera utilisée
    pour stocker les informations supplémentaires des utilisateurs.

    Opérations:
    1. Création du modèle 'Profile' avec les champs:
       - id (clé primaire auto-générée)
       - favorite_city (ville préférée de l'utilisateur, optionnelle)
       - user (relation OneToOne vers le modèle User d'authentification)

    Relations:
    - Une relation OneToOne est établie avec le modèle User (AUTH_USER_MODEL)
    - Le related_name 'profile_new' est utilisé temporairement pour éviter les conflits
      avec l'ancienne application 'profiles' (sera modifié dans une migration ultérieure)
    """

    initial = True

    dependencies = [
        # Dépendance vers le système d'authentification de Django
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorite_city", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_new",  # Nom temporaire pour la relation
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
