# Generated by Django 4.2.21 on 2025-05-25 16:49
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration de correction de la relation User-Profile.
    Cette migration met à jour le nom de la relation (related_name) entre
    les modèles User et Profile pour utiliser le nom standard 'profile'
    au lieu du nom temporaire 'profile_new'.
    Objectifs:
    1. Uniformiser le nom d'accès aux profils depuis les utilisateurs
    2. Résoudre les conflits potentiels avec d'autres applications
    3. Préparer la suppression de l'ancienne application 'profiles'
    Opération:
    - Modification du champ 'user' dans le modèle Profile:
      * related_name changé de 'profile_new' à 'profile'
    Dépendances:
    - Dépend de la migration de copie de données (0002_copy_data)
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0002_copy_data"),
    ]
    operations = [
        migrations.AlterField(
            model_name="Profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                # Nom final de la relation
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
