# .readthedocs.yaml
# Docs : https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"   # garde 3.12 pour être aligné avec ton projet local
  # Optionnel : allonger le timeout si nécessaire
  # jobs:
  #   build:
  #     timeout: 1200  # secondes

sphinx:
  configuration: docs/source/conf.py
  # Passe à true quand tout est propre pour "fail on warnings"
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt

# Formats additionnels (optionnels)
formats:
  - htmlzip
  - pdf
  - epub
