# .readthedocs.yaml
# Docs : https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false   # passe à true quand c'est propre

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub
