"""
Migration initiale pour l'application 'lettings'
Crée deux modèles essentiels :
1. Address - Modèle d'adresse postale
2. Letting - Modèle d'annonce de location avec relation vers Address
Détails des modèles:
--- Address ---
Champs:
- id: Clé primaire auto-générée (BigAutoField)
- number: Numéro de rue (1-9999)
- street: Nom de rue (max 64 caractères)
- city: Ville (max 64 caractères)
- state: État/Province (code à 2 lettres)
- zip_code: Code postal (5 chiffres)
- country_iso_code: Code pays ISO (3 lettres)
Validations:
- number et zip_code: Valeurs max 9999 et 99999
- state et country_iso_code: Longueur exacte (2 et 3 caractères)
--- Letting ---
Champs:
- id: Clé primaire auto-générée (BigAutoField)
- title: Titre de l'annonce (max 256 caractères)
- address: Relation OneToOne vers Address (suppression en cascade)
Relations:
- Une Letting est liée à une seule Address
- Si une Address est supprimée, la Letting associée est automatiquement supprimée
Opérations:
- Création de la table 'lettings_address'
- Création de la table 'lettings_letting' avec clé étrangère vers Address
Dépendances:
- Aucune (migration initiale)
"""

# Generated by Django 4.2.21 on 2025-05-25 16:05
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(9999)]
                    ),
                ),
                ("street", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        max_length=2,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "zip_code",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999)]
                    ),
                ),
                (
                    "country_iso_code",
                    models.CharField(
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Letting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lettings.address",
                    ),
                ),
            ],
        ),
    ]
