"""
Migration initiale pour l'application oc_lettings_site.
Crée trois modèles principaux :
1. Address - Stocke les informations d'adresse postale
   Champs:
   - number: Numéro dans la rue (entier positif <= 9999)
   - street: Nom de la rue (max 64 caractères)
   - city: Ville (max 64 caractères)
   - state: État/Province (code à 2 lettres)
   - zip_code: Code postal (entier positif <= 99999)
   - country_iso_code: Code pays ISO (3 lettres)
2. Profile - Extension du modèle utilisateur Django
   Champs:
   - favorite_city: Ville préférée (optionnelle, max 64 caractères)
   - user: Relation OneToOne avec le modèle User (clé étrangère)
3. Letting - Annonce de location immobilière
   Champs:
   - title: Titre de l'annonce (max 256 caractères)
   - address: Relation OneToOne avec Address (clé étrangère)
Dépendances:
- Utilise le modèle utilisateur par défaut de Django (settings.AUTH_USER_MODEL)
"""

# Generated by Django 3.0 on 2020-06-14 09:35
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(9999)]
                    ),
                ),
                ("street", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        max_length=2,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "zip_code",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999)]
                    ),
                ),
                (
                    "country_iso_code",
                    models.CharField(
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorite_city", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Letting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oc_lettings_site.Address",
                    ),
                ),
            ],
        ),
    ]
