"""
Migration de suppression des modèles pour l'application oc_lettings_site.
Effectue une suppression en cascade des modèles précédemment créés :
1. Supprime la relation 'address' du modèle Letting
2. Supprime la relation 'user' du modèle Profile
3. Supprime définitivement les modèles:
   - Address
   - Letting
   - Profile
Dépendances:
- Dépend de la migration initiale (0001_initial)
"""

# Generated by Django 4.2.21 on 2025-05-25 16:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0001_initial"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="letting",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Letting",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
